"""
ETF Analyzer: ETF profili, holdings breakdown, sektör dağılımı, performans karşılaştırması.
"""
from __future__ import annotations

ETF_DB: dict[str, dict] = {
    "SPY": {
        "name": "SPDR S&P 500 ETF Trust",
        "description": "S&P 500 endeksini takip eden dünyanın en büyük ETF'i. 500 büyük ABD şirketini kapsar.",
        "expense_ratio": 0.0945,
        "aum_bn": 548.2,
        "inception": "1993-01-22",
        "benchmark": "S&P 500",
        "currency": "USD",
        "price": 561.4,
        "ytd_pct": 14.8,
        "1y_pct": 22.4,
        "3y_ann_pct": 10.2,
        "5y_ann_pct": 14.8,
        "dividend_yield": 1.28,
        "pe_ratio": 24.2,
        "top_holdings": [
            {"ticker": "AAPL",  "name": "Apple Inc.",          "weight_pct": 7.12},
            {"ticker": "MSFT",  "name": "Microsoft Corp.",     "weight_pct": 6.84},
            {"ticker": "NVDA",  "name": "NVIDIA Corp.",        "weight_pct": 6.42},
            {"ticker": "AMZN",  "name": "Amazon.com Inc.",     "weight_pct": 3.84},
            {"ticker": "META",  "name": "Meta Platforms",      "weight_pct": 2.68},
            {"ticker": "GOOGL", "name": "Alphabet Inc. A",     "weight_pct": 2.12},
            {"ticker": "TSLA",  "name": "Tesla Inc.",          "weight_pct": 1.96},
            {"ticker": "BRK.B", "name": "Berkshire Hathaway",  "weight_pct": 1.82},
            {"ticker": "JPM",   "name": "JPMorgan Chase",      "weight_pct": 1.74},
            {"ticker": "LLY",   "name": "Eli Lilly & Co.",     "weight_pct": 1.58},
        ],
        "sector_weights": [
            {"sector": "Bilişim", "weight_pct": 31.2},
            {"sector": "Sağlık", "weight_pct": 12.8},
            {"sector": "Finans", "weight_pct": 12.4},
            {"sector": "Tüketici (İsteğe Bağlı)", "weight_pct": 10.8},
            {"sector": "Sanayi", "weight_pct": 8.6},
            {"sector": "İletişim", "weight_pct": 8.4},
            {"sector": "Tüketici (Zorunlu)", "weight_pct": 5.8},
            {"sector": "Enerji", "weight_pct": 3.8},
            {"sector": "Diğer", "weight_pct": 6.2},
        ],
        "risk_metrics": {"beta": 1.00, "std_dev_ann": 15.2, "sharpe_ratio": 0.84, "max_drawdown": -33.9},
    },
    "QQQ": {
        "name": "Invesco QQQ Trust",
        "description": "NASDAQ-100 endeksini takip eder. Teknoloji ağırlıklı büyük şirketleri kapsar.",
        "expense_ratio": 0.20,
        "aum_bn": 298.4,
        "inception": "1999-03-10",
        "benchmark": "NASDAQ-100",
        "currency": "USD",
        "price": 482.8,
        "ytd_pct": 18.6,
        "1y_pct": 28.4,
        "3y_ann_pct": 10.8,
        "5y_ann_pct": 21.4,
        "dividend_yield": 0.54,
        "pe_ratio": 34.8,
        "top_holdings": [
            {"ticker": "AAPL",  "name": "Apple Inc.",       "weight_pct": 9.12},
            {"ticker": "MSFT",  "name": "Microsoft Corp.",  "weight_pct": 8.64},
            {"ticker": "NVDA",  "name": "NVIDIA Corp.",     "weight_pct": 8.42},
            {"ticker": "AMZN",  "name": "Amazon.com Inc.",  "weight_pct": 5.24},
            {"ticker": "META",  "name": "Meta Platforms",   "weight_pct": 4.82},
            {"ticker": "TSLA",  "name": "Tesla Inc.",       "weight_pct": 3.96},
            {"ticker": "GOOGL", "name": "Alphabet Inc. A",  "weight_pct": 3.12},
            {"ticker": "AVGO",  "name": "Broadcom Inc.",    "weight_pct": 2.84},
            {"ticker": "COST",  "name": "Costco Wholesale", "weight_pct": 2.48},
            {"ticker": "NFLX",  "name": "Netflix Inc.",     "weight_pct": 2.14},
        ],
        "sector_weights": [
            {"sector": "Bilişim", "weight_pct": 52.4},
            {"sector": "İletişim", "weight_pct": 18.2},
            {"sector": "Tüketici (İsteğe Bağlı)", "weight_pct": 14.8},
            {"sector": "Sağlık", "weight_pct": 6.4},
            {"sector": "Sanayi", "weight_pct": 4.8},
            {"sector": "Diğer", "weight_pct": 3.4},
        ],
        "risk_metrics": {"beta": 1.18, "std_dev_ann": 18.4, "sharpe_ratio": 0.91, "max_drawdown": -35.2},
    },
    "GLD": {
        "name": "SPDR Gold Shares",
        "description": "Fiziksel altın fiyatını takip eder. Enflasyon ve jeopolitik risk koruması için kullanılır.",
        "expense_ratio": 0.40,
        "aum_bn": 74.2,
        "inception": "2004-11-18",
        "benchmark": "Altın Spot Fiyatı",
        "currency": "USD",
        "price": 318.4,
        "ytd_pct": 22.8,
        "1y_pct": 31.4,
        "3y_ann_pct": 12.8,
        "5y_ann_pct": 11.4,
        "dividend_yield": 0.0,
        "pe_ratio": None,
        "top_holdings": [
            {"ticker": "GOLD", "name": "Fiziksel Altın (Ons)", "weight_pct": 99.7},
        ],
        "sector_weights": [
            {"sector": "Değerli Metaller", "weight_pct": 100.0},
        ],
        "risk_metrics": {"beta": 0.04, "std_dev_ann": 12.8, "sharpe_ratio": 0.72, "max_drawdown": -18.4},
    },
    "ARKK": {
        "name": "ARK Innovation ETF",
        "description": "Yıkıcı inovasyon teknolojilerine odaklanan aktif yönetilen ETF. Yüksek risk/yüksek getiri profili.",
        "expense_ratio": 0.75,
        "aum_bn": 8.4,
        "inception": "2014-10-31",
        "benchmark": "S&P 500",
        "currency": "USD",
        "price": 68.4,
        "ytd_pct": 12.4,
        "1y_pct": 18.8,
        "3y_ann_pct": -8.4,
        "5y_ann_pct": 4.2,
        "dividend_yield": 0.0,
        "pe_ratio": 48.2,
        "top_holdings": [
            {"ticker": "TSLA",  "name": "Tesla Inc.",       "weight_pct": 9.84},
            {"ticker": "COIN",  "name": "Coinbase Global",  "weight_pct": 8.42},
            {"ticker": "ROKU",  "name": "Roku Inc.",        "weight_pct": 7.28},
            {"ticker": "SHOP",  "name": "Shopify Inc.",     "weight_pct": 6.84},
            {"ticker": "SPOT",  "name": "Spotify Tech.",    "weight_pct": 6.12},
            {"ticker": "PATH",  "name": "UiPath Inc.",      "weight_pct": 5.48},
            {"ticker": "CRSP",  "name": "CRISPR Therapeutics","weight_pct": 4.82},
            {"ticker": "EXAS",  "name": "Exact Sciences",  "weight_pct": 4.24},
            {"ticker": "SQ",    "name": "Block Inc.",       "weight_pct": 3.98},
            {"ticker": "TWLO",  "name": "Twilio Inc.",      "weight_pct": 3.42},
        ],
        "sector_weights": [
            {"sector": "Bilişim & Yazılım", "weight_pct": 38.4},
            {"sector": "Sağlık & Biyoteknoloji", "weight_pct": 24.8},
            {"sector": "Fintech", "weight_pct": 18.2},
            {"sector": "Tüketim & Medya", "weight_pct": 12.4},
            {"sector": "Diğer", "weight_pct": 6.2},
        ],
        "risk_metrics": {"beta": 1.62, "std_dev_ann": 42.8, "sharpe_ratio": 0.28, "max_drawdown": -75.2},
    },
    "XLF": {
        "name": "Financial Select Sector SPDR Fund",
        "description": "S&P 500 finans sektörü şirketlerini kapsar. Bankalar, sigorta, yatırım şirketleri.",
        "expense_ratio": 0.09,
        "aum_bn": 42.8,
        "inception": "1998-12-16",
        "benchmark": "S&P 500 Financial Sector",
        "currency": "USD",
        "price": 48.2,
        "ytd_pct": 8.4,
        "1y_pct": 18.2,
        "3y_ann_pct": 8.8,
        "5y_ann_pct": 12.4,
        "dividend_yield": 1.84,
        "pe_ratio": 14.8,
        "top_holdings": [
            {"ticker": "BRK.B", "name": "Berkshire Hathaway", "weight_pct": 13.42},
            {"ticker": "JPM",   "name": "JPMorgan Chase",     "weight_pct": 11.84},
            {"ticker": "V",     "name": "Visa Inc.",          "weight_pct": 8.42},
            {"ticker": "MA",    "name": "Mastercard Inc.",    "weight_pct": 6.84},
            {"ticker": "BAC",   "name": "Bank of America",   "weight_pct": 4.28},
            {"ticker": "GS",    "name": "Goldman Sachs",     "weight_pct": 3.84},
            {"ticker": "MS",    "name": "Morgan Stanley",    "weight_pct": 3.42},
            {"ticker": "WFC",   "name": "Wells Fargo",       "weight_pct": 3.12},
            {"ticker": "AXP",   "name": "American Express",  "weight_pct": 2.84},
            {"ticker": "SPGI",  "name": "S&P Global Inc.",   "weight_pct": 2.48},
        ],
        "sector_weights": [
            {"sector": "Bankacılık", "weight_pct": 38.4},
            {"sector": "Sigorta", "weight_pct": 18.2},
            {"sector": "Sermaye Piyasaları", "weight_pct": 24.8},
            {"sector": "Ödeme Sistemleri", "weight_pct": 14.8},
            {"sector": "Diğer", "weight_pct": 3.8},
        ],
        "risk_metrics": {"beta": 1.12, "std_dev_ann": 18.8, "sharpe_ratio": 0.68, "max_drawdown": -44.8},
    },
    "BIST30ETF": {
        "name": "Ziraat BIST 30 ETF",
        "description": "BIST 30 endeksini takip eder. Türkiye borsasının en likit 30 hissesini kapsar.",
        "expense_ratio": 0.35,
        "aum_bn": 2.4,
        "inception": "2012-06-14",
        "benchmark": "BIST 30",
        "currency": "TRY",
        "price": 48.82,
        "ytd_pct": 21.4,
        "1y_pct": 38.4,
        "3y_ann_pct": 84.2,
        "5y_ann_pct": 112.8,
        "dividend_yield": 2.84,
        "pe_ratio": 7.2,
        "top_holdings": [
            {"ticker": "GARAN", "name": "Garanti BBVA",      "weight_pct": 8.42},
            {"ticker": "THYAO", "name": "Türk Hava Yolları", "weight_pct": 7.84},
            {"ticker": "ASELS", "name": "Aselsan",           "weight_pct": 6.24},
            {"ticker": "EREGL", "name": "Ereğli Demir",      "weight_pct": 5.82},
            {"ticker": "SISE",  "name": "Şişecam",           "weight_pct": 4.48},
            {"ticker": "AKBNK", "name": "Akbank",            "weight_pct": 6.84},
            {"ticker": "ISCTR", "name": "İş Bankası",        "weight_pct": 6.12},
            {"ticker": "KCHOL", "name": "Koç Holding",       "weight_pct": 5.84},
            {"ticker": "BIMAS", "name": "BİM Mağazalar",     "weight_pct": 4.28},
            {"ticker": "TOASO", "name": "Tofaş Otomobil",   "weight_pct": 3.82},
        ],
        "sector_weights": [
            {"sector": "Bankacılık & Finans", "weight_pct": 32.4},
            {"sector": "Sanayi", "weight_pct": 18.8},
            {"sector": "Havacılık", "weight_pct": 7.8},
            {"sector": "Savunma", "weight_pct": 6.2},
            {"sector": "Perakende", "weight_pct": 8.4},
            {"sector": "Enerji", "weight_pct": 6.8},
            {"sector": "Diğer", "weight_pct": 19.6},
        ],
        "risk_metrics": {"beta": None, "std_dev_ann": 28.4, "sharpe_ratio": 1.12, "max_drawdown": -42.4},
    },
}

ETF_LIST = list(ETF_DB.keys())


def get_etf(symbol: str) -> dict | None:
    return ETF_DB.get(symbol.upper())


def compare_etfs(symbols: list[str]) -> list[dict]:
    result = []
    for s in symbols:
        data = ETF_DB.get(s.upper())
        if data:
            result.append({
                "symbol": s.upper(),
                "name": data["name"],
                "price": data["price"],
                "currency": data["currency"],
                "expense_ratio": data["expense_ratio"],
                "aum_bn": data["aum_bn"],
                "ytd_pct": data["ytd_pct"],
                "1y_pct": data["1y_pct"],
                "3y_ann_pct": data["3y_ann_pct"],
                "dividend_yield": data["dividend_yield"],
                "pe_ratio": data["pe_ratio"],
                "risk_metrics": data["risk_metrics"],
            })
    return result
